name: Full Org Backup to SolvevareBackup

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:       # allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Mirror all repos from solvevare-org to SolvevareBackup
        run: |
          MAIN_ORG="solvevare-org"
          BACKUP_ORG="SolvevareBackup"

          # Get all repos from solvevare-org (paginate through results)
          page=1
          > repo_list.txt
          while true; do
            response=$(curl -s -H "Authorization: token ${{ secrets.BACKUP_TOKEN }}" \
              "https://api.github.com/orgs/$MAIN_ORG/repos?per_page=100&page=$page")
            count=$(echo "$response" | jq length)
            if [ "$count" -eq 0 ]; then
              break
            fi
            echo "$response" | jq -r '.[].name' >> repo_list.txt
            page=$((page+1))
          done

          while read REPO_NAME; do
            echo "=== Processing $REPO_NAME ==="

            # Check if backup repo exists in SolvevareBackup
            STATUS=$(curl -o /dev/null -s -w "%{http_code}" \
              -H "Authorization: token ${{ secrets.BACKUP_TOKEN }}" \
              https://api.github.com/repos/$BACKUP_ORG/$REPO_NAME)

            if [ "$STATUS" -eq 404 ]; then
              echo "Creating backup repo $BACKUP_ORG/$REPO_NAME"
              curl -s -X POST \
                -H "Authorization: token ${{ secrets.BACKUP_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/orgs/$BACKUP_ORG/repos \
                -d "{\"name\":\"$REPO_NAME\",\"private\":true}"
            fi

            # Mirror push
            git clone --mirror https://github:${{ secrets.BACKUP_TOKEN }}@github.com/$MAIN_ORG/$REPO_NAME.git
            cd $REPO_NAME.git
            git remote add backup https://github:${{ secrets.BACKUP_TOKEN }}@github.com/$BACKUP_ORG/$REPO_NAME.git
            git push --mirror backup || echo "⚠️ Failed to push $REPO_NAME"
            cd ..
            rm -rf $REPO_NAME.git
          done < repo_list.txt
