name: CI/CD Docker Deploy

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          IMAGE: ${{ secrets.DOCKER_USERNAME }}/express-app
          TAG: ${{ github.sha }}
        run: |
          docker build -t $IMAGE:latest -t $IMAGE:$TAG .
          docker push $IMAGE:latest
          docker push $IMAGE:$TAG

      - name: Deploy to VPS (run deploy.sh)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/express-app
            TAG=${{ github.sha }}
            /bin/bash /opt/deploy/deploy.sh "$IMAGE" "$TAG"
